# CUDA_VISIBLE_DEVICES=3 python feddyn.py --seed 0 --epochs 1 --round 100 --batch_size 16 --dataset "cifar10" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/500client"
# CUDA_VISIBLE_DEVICES=1,0,3,2 python scaffold.py --seed 0 --epochs 5 --round 5 --batch_size 16 --dataset "cifar10" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/500client"
# CUDA_VISIBLE_DEVICES=2 python fednova.py --seed 0 --epochs 5 --round 300 --batch_size 16 --dataset "cifar10" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/500client" > fednova.log &
# CUDA_VISIBLE_DEVICES=2 python fedprox.py --seed 0 --epochs 5 --round 300 --batch_size 16 --dataset "cifar10" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/500client" > fedprox.log &
# CUDA_VISIBLE_DEVICES=3 python singleset.py --wandb 0 --seed 0 --verbose 0 --epochs 5 --round 500 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client" > singleset.log &
# CUDA_VISIBLE_DEVICES=3 python fedavg.py --wandb 0 --seed 0 --verbose 0 --epochs 5 --round 500 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client" > fedavg.log &
# CUDA_VISIBLE_DEVICES=3 python fedprox.py --wandb 0 --seed 0 --verbose 0 --epochs 5 --round 500 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client" > fedprox.log &
# CUDA_VISIBLE_DEVICES=3 python fednova.py --wandb 0 --seed 0 --verbose 0 --epochs 5 --round 500 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client" > fednova.log &
# CUDA_VISIBLE_DEVICES=2,3,1 python scaffold.py --wandb 0 --seed 0 --verbose 0 --epochs 5 --round 500 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client"
# CUDA_VISIBLE_DEVICES=2,3,1 python feddyn.py --wandb 0 --seed 0 --verbose 0 --epochs 5 --round 500 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client"
# CUDA_VISIBLE_DEVICES=3 python fim.py --wandb 0 --seed 0 --verbose 1 --epochs 100 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_1_sparse/300client"
# CUDA_VISIBLE_DEVICES=2 python fim.py --wandb 0 --seed 0 --verbose 1 --epochs 1 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/100client"
# CUDA_VISIBLE_DEVICES=2 python fedavg.py --wandb 0 --seed 0 --verbose 0 --round 100 --epochs 1 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/100client"
# CUDA_VISIBLE_DEVICES=2 python fim.py --seed 0 --epochs 0 --batch_size 16 --dataset "cifar10" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/500client"


CUDA_VISIBLE_DEVICES=1 python fim.py --wandb 0 --seed 0 --verbose 1 --epochs 100 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/100client"
CUDA_VISIBLE_DEVICES=1 python fedavg+fim.py --wandb 0 --seed 0 --verbose 0 --round 100 --epochs 5 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/100client"
CUDA_VISIBLE_DEVICES=1 python fednova+fim.py --wandb 0 --seed 0 --verbose 0 --round 100 --epochs 5 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/100client"
# CUDA_VISIBLE_DEVICES=1 python fedavg+fim.py --wandb 0 --seed 0 --verbose 0 --round 100 --epochs 1 --batch_size 16 --dataset "cifar10" --data_folder "../perFL/benchmark/cifar10/data" --idx_folder "./jsons/dataset_idx/cifar10/dirichlet/dir_0.1_sparse/100client"
